export const actionType = {
  ADD_DATA: "ADD_DATA",
  MINUS_DATA: "MINUS_DATA",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_ERROR: "FETCH_USERS_ERROR",
  ONCHANGE_ID: "ONCHANGE_ID",
};
